config/routes.rb
Immageup::Application.routes.draw do
  resources :albums
  resources :users
  resources :assets
  match ':controller(/:action(/:id))(.:format)' 
  root :to => 'home#index'

get "new_user" => "users#new"
post "sign_in" => "authentication#login"
get "sign_in" => "authentication#sign_in"
get "signed_out" => "authentication#signed_out"
get "adminpanel" => "users#adminpanel"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :albumName, :description, :albumAvatar, :assets
  belongs_to :user
  has_many :assets, dependent: :destroy
  
  validates_uniqueness_of :albumName, :scope => [:user_id]
  validates :albumName, :presence => true
  
  has_attached_file :albumAvatar,:dependent => :destroy, :default_url => '/defaultAlbumProfile.png'
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    @counter=0
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @counter=0
    @album = Album.find(params[:id])
    @user = User.find(@album.user_id)
    if session[:album_id]=params[:id]
    flash= 'This album was set as active. Viewing an album sets it as active!'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
  if current_user
    @album = current_user.albums.build(params[:album])
  end
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :albumName %><br />
    <%= f.text_field :albumName %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
<strong>Album cover picture</strong> 
	<%= f.file_field :albumAvatar %> <br/>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', @album %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table cellspacing="23" >
  <tr>
    <th>Album Name</th>
    <th>Description</th>
    <th>User</th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.albumName %></td>
    <td><%= album.description %></td>
    <td><%= link_to album.user_id, "/users/#{album.user_id}"%></td>
	
 <td><%= image_tag album.albumAvatar %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Created by </h3> 
	<p><%= link_to @user.name ,@user %>
</p>
<p>
  <b>Album Name</b>
  <%= @album.albumName %>
</p>

<p>
  <b>Description</b>
  <%= @album.description %>
</p>

	
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', current_user %>





 
<center>
<noformat>
<table border="1" bordercolor="993300" cellspacing="2" cellpadding="2">
<tbody><tr>
<% if @album.assets.any? %>
<% @album.assets.each do |u| %>

<% @counter=@counter+1 %>

<th> <div align="center" class="image" style="width: 222px;">
<%= link_to image_tag(u.asset.url, :class => "style_image"),u %>
<br>
<span class="caption"><%= u.asset.original_filename %></span></div> </th>
<% if @counter % 3 ==0 %>
<tr></tr>
<% end %>
<% end %>

<% end %>					</tr>
				</tbody>
			</table>
		</noformat>
	</center>