config/routes.rb
Immageup::Application.routes.draw do
  resources :albums
  resources :users
  resources :assets
  match ':controller(/:action(/:id))(.:format)' 
  root :to => 'home#index'

get "new_user" => "users#new"
post "sign_in" => "authentication#login"
get "sign_in" => "authentication#sign_in"
get "signed_out" => "authentication#signed_out"
get "adminpanel" => "users#adminpanel"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :asset
  belongs_to :user
  belongs_to :album
  has_attached_file :asset, dependent: :destroy
  
  validates_attachment_presence :asset  
  validates_attachment_content_type :asset, 
  :content_type => /^image\/(png|gif|jpeg|jpg|bmp)/
  
   
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	@counter = 0
  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  # GET /assets/1
 # GET /assets/1.json
    def show
      @asset = Asset.find(params[:id])
      @user = User.find(@asset.user_id)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @asset }
      end
    end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
	if current_user
    @asset = current_user.assets.build(params[:asset])
    
    @asset.album=Album.find_by_id(activeAlbumId)
	end
    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset, :html => {:multipart => true}) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label :Pictueeee_upload %><br />
    <%= f.file_field :asset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assets.each do |asset| %>
  <tr><td>
  <div class="bottom-margin">
	<div class="imageContainer">
	<%= image_tag asset.asset.url %>  
	</div>
</div>  
	</td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
    <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>


  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<h3> Uploaded by <td><%= link_to  @user.name, @user %></td>
<div class="bottom-margin">
	<%= image_tag @asset.asset.url, :style => "max-height:75%;" %>
</div>  
<% if current_user %>
<% if current_user.id==@asset.user_id || current_user.isadmin %>
<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Destroy', @asset, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% end %>|
<%= link_to 'Back', root_path %>
</center>
</h3> 