config/routes.rb
Immageup::Application.routes.draw do
  resources :albums
  resources :users
  resources :assets
  match ':controller(/:action(/:id))(.:format)' 
  root :to => 'home#index'

get "new_user" => "users#new"
post "sign_in" => "authentication#login"
get "sign_in" => "authentication#sign_in"
get "signed_out" => "authentication#signed_out"
get "adminpanel" => "users#adminpanel"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<html>
<head>
  <title>Immageup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<meta name="robots" content="follow,index"/>
<meta name="keywords" content="images, funny pictures, image host, image upload, image sharing, image resize"/>
<meta name="description" content="imageup is used to upload and show photos, and has the funniest pictures from all over the Internet."/>
<link rel="stylesheet" type="text/css" href="tempstyle.css"/>
<%= stylesheet_link_tag "tempstyle.css.scss" %>
</head>

<div class="menuBar">

<div id="topbar">



    <div id="header-logo"> 
<%= link_to image_tag("logoIcon.png", :height => "100%"),root_path%></div>
	
    <% if current_user %>


    <div id="signout">
<%= link_to image_tag("signout.png", :height => "100%" ), signed_out_path %> </div>
    <% if current_user.isadmin %>

    <div id="signout"> 
<%= link_to image_tag("admin.png", :height => "100%"), "/adminpanel"%></div>
<% end %>


    <div id="username">
	<h11>
    <%= current_user.name %></h11></div>


<div id="avatarBox">
       <%= link_to image_tag(current_user.avatar.url,{:height => "43px", :class =>"avatar"}),current_user%></div>

  <% else %>
       <div id="signin">
<%= link_to image_tag("signin.png", :height => "100%" ),"/sign_in" %> </div>
       <div id="register">
<%= link_to image_tag("register.png",:height => "100%"),"/new_user"%> </div>
  <% end %>

</div>
  </div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<%= yield %>
<div id="footer">
		<!-- Footer start -->
		<p><strong>Immageup by Namik Karovic</strong> <a href="mailto:namik_karovic@hotmail.com">Email Me</a>
    </p>
		<!-- Footer end -->
	</div>

</html>